// <auto-generated>
// Rewired Constants
// This list was generated on 6/22/2020 2:59:03 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Quit")]
        public const int Quit = 0;
        // Ship
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Ship", friendlyName = "Turn")]
        public const int Turn = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Ship", friendlyName = "Shoot")]
        public const int Shoot = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Ship", friendlyName = "Throw Bomb")]
        public const int Bomb = 6;
        // ToySoldier
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Toy Soldier", friendlyName = "Walk Vertical")]
        public const int WalkVertical = 5;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Toy Soldier", friendlyName = "Walk Horizontal")]
        public const int WalkHorizontal = 4;
        // Menu
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu", friendlyName = "Menu Vertical")]
        public const int MenuVertical = 7;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu", friendlyName = "Menu Horizontal")]
        public const int MenuHorizontal = 8;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu", friendlyName = "Menu Select")]
        public const int MenuSelect = 9;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu", friendlyName = "Menu Back")]
        public const int MenuBack = 10;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu", friendlyName = "Start")]
        public const int Start = 11;
    }
    public static partial class Category {
        public const int Default = 0;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player 1")]
        public const int Player1 = 0;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player 2")]
        public const int Player2 = 1;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player 3")]
        public const int Player3 = 2;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player 4")]
        public const int Player4 = 3;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player Keyboard")]
        public const int PlayerKeyboard = 4;
    }
    public static partial class CustomController {
    }
    public static partial class LayoutManagerRuleSet {
    }
    public static partial class MapEnablerRuleSet {
        public const int DisableAll = 1;
        public const int EnableAll = 2;
    }
}
